### PR TITLE
Require `rails-data-migrations` explicitly

### PR DESCRIPTION
**Pull request by bolshakov**
Without this require, it will fail when used with rails engine.

### CODE REVIEW

**Comment by serggl** [comment]
Which version of Rails was causing problems?
Just curious why specs were not failing for me...

**Comment by bolshakov** [comment]
Specs does not fail for you because you've loaded `railse-data-migrations` in `spec_helper.rb`. I'm using the gem outside of a rails project. 

And I have binstub for rails:

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true
# This command will automatically be run when you run "rails" with Rails 4 gems
# installed from the root of your application.

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/subscriptions/engine', __FILE__)

# Set up gems listed in the Gemfile.
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
require 'bundler/setup' if File.exist?(ENV['BUNDLE_GEMFILE'])

require 'rails/all'
require 'rails/engine/commands'
```

**Comment by serggl** [comment]
Will this work if we add `unless defined?(Rails)` at the end of this require line?

**Comment by bolshakov** [comment]
The problem is not in the absence of Rails constant. It fails to locate DataMigrationGenerator itself. Here is the full backtrace:

```
✗ rails generate data_migration create_autorenews
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rails-data-migrations-1.0.4/lib/generators/data_migration_generator.rb:7:in `create_migration_file': uninitialized constant DataMigrationGenerator::RailsDataMigrations (NameError)
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:157:in `invoke'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine/commands.rb:19:in `<top (required)>'
	from bin/rails:14:in `require'
	from bin/rails:14:in `<main>'
```

**Comment by serggl** [comment]
I would love to see a spec that fail without this additional require

**Comment by bolshakov** [comment]
I've mentioned way to reproduce the issue [here](https://github.com/OffgridElectric/rails-data-migrations/issues/4). I don't think it's reasonable to write such kind of tests.

**Pull request merged**
